numbers = [8,1,2,3,4,5]
# numbers.append(6)
# print('numbers',numbers)
# numbers.insert(0,0)
# print('numbers',numbers)
# numbers.remove(1)
# print('numbers',numbers)
# numbers.pop(1)
# print('numbers',numbers)
# numbers.pop(0)
# print('numbers',numbers)
# numbers.pop(1)
# print('numbers',numbers)
# numbers.clear()
# print('numbers',numbers)
# numbers.copy()
# print('numbers',numbers)
# numbers.sort()
# print('numbers',numbers)
numbers.reverse()
print('numbers',numbers)